/**
 * Generates the app theme (src/generated/theme.ts) and the widget constants
 * (src/generated/widget-constants.json) from design/tokens.json.
 *
 *   npm run tokens
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { mix } from '../src/color';

type Hex = string;
interface AccentInput {
  accent: Hex;
  edge: Hex;
  onAccent: Hex;
}

const here = dirname(fileURLToPath(import.meta.url));
const tokensPath = resolve(here, '../../../design/tokens.json');
const outDir = resolve(here, '../src/generated');
const tokens = JSON.parse(readFileSync(tokensPath, 'utf8'));

const schemes = ['light', 'dark'] as const;
const { neutral, game, liturgical, derive, pax } = tokens.color;

const palettes: Record<string, unknown> = {};
for (const [name, def] of Object.entries<Record<string, unknown>>(liturgical)) {
  if (name.startsWith('$')) continue;
  const out: Record<string, unknown> = { label: def.label };
  for (const scheme of schemes) {
    const input = def[scheme] as AccentInput;
    const background: Hex = neutral[scheme].background;
    const tint =
      scheme === 'light'
        ? mix(input.accent, '#FFFFFF', derive.tintLight)
        : mix(input.accent, background, derive.tintDark);
    // Accent-colored text: the raised edge reads well on white; on dark, lighten the accent.
    const text =
      scheme === 'light' ? input.edge : mix(input.accent, '#FFFFFF', derive.accentTextDarkTowardWhite);
    out[scheme] = { ...input, tint, text };
  }
  palettes[name] = out;
}

const theme = {
  version: tokens.version,
  neutral,
  game,
  palettes,
  pax,
  font: tokens.font,
  radius: tokens.radius,
  border: tokens.border,
  edge: tokens.edge,
  space: tokens.space,
  size: tokens.size,
};

mkdirSync(outDir, { recursive: true });
writeFileSync(
  resolve(outDir, 'theme.ts'),
  `// Generated by packages/tokens/scripts/build.ts from design/tokens.json. Do not edit.\n` +
    `export const tokens = ${JSON.stringify(theme, null, 2)} as const;\n`,
);

// Flat constants for the native widgets (Swift / Kotlin read this file at build time).
const widget = {
  version: tokens.version,
  fontFamily: tokens.font.family.ui,
  neutral: { light: neutral.light, dark: neutral.dark },
  game,
  palettes,
};
writeFileSync(resolve(outDir, 'widget-constants.json'), JSON.stringify(widget, null, 2) + '\n');
console.log(`Generated theme and widget constants from ${tokensPath}`);
