import data from './data/lectionary.json';
import type { LectionaryCycle, Rank, ReadingCitations, SundayCycle, WeekdayCycle } from './types';

/**
 * Bundled lectionary, generated by `pipeline/build_content.py` from the same rows as the
 * `lectionary` table in content.db. Keyed `"<romcal key>|<cycle>"`; each value is
 * [first reading, psalm, second reading ("" when none), gospel].
 */
interface LectionaryFile {
  contentVersion: string;
  entries: Record<string, [string, string, string, string]>;
}

const lectionary = data as unknown as LectionaryFile;

export const lectionaryContentVersion = lectionary.contentVersion;

const ALL_CYCLES: LectionaryCycle[] = ['A', 'B', 'C', 'I', 'II'];

/** Ranks whose readings follow the Sunday cycle (A/B/C) and replace the weekday's. */
const PROPER_RANKS: ReadonlySet<Rank> = new Set(['SOLEMNITY', 'SUNDAY', 'FEAST']);

export interface LectionaryQuery {
  key: string;
  weekdayKey: string | null;
  rank: Rank;
  sundayCycle: SundayCycle;
  weekdayCycle: WeekdayCycle;
}

/**
 * Solemnities, Sundays and feasts use their own readings in the Sunday cycle. Weekdays and
 * memorials use the weekday's readings in the weekday cycle (memorials with proper readings
 * are not in the v1 data yet).
 */
export function lookupReadings(q: LectionaryQuery): {
  readings: ReadingCitations | null;
  cycle: LectionaryCycle;
} {
  const ferial = q.weekdayKey ?? q.key;
  const candidates: [string, LectionaryCycle][] = PROPER_RANKS.has(q.rank)
    ? [
        [q.key, q.sundayCycle],
        [q.key, q.weekdayCycle],
      ]
    : [
        [ferial, q.weekdayCycle],
        [q.key, q.weekdayCycle],
        [q.key, q.sundayCycle],
      ];
  for (const [key, cycle] of candidates) {
    const row = lectionary.entries[`${key}|${cycle}`];
    if (row) return { readings: toCitations(row), cycle };
  }
  // Same readings every year (e.g. a fixed feast seen only in another cycle so far).
  for (const cycle of ALL_CYCLES) {
    const row = lectionary.entries[`${q.key}|${cycle}`];
    if (row) return { readings: toCitations(row), cycle };
  }
  return {
    readings: null,
    cycle: PROPER_RANKS.has(q.rank) ? q.sundayCycle : q.weekdayCycle,
  };
}

function toCitations([firstReading, psalm, secondReading, gospel]: [
  string,
  string,
  string,
  string,
]): ReadingCitations {
  return { firstReading, psalm, secondReading: secondReading || null, gospel };
}
